In [1]:
from keras.models import Model
from keras.models import load_model
from dataset_loaders import SimpleDatasetLoader
from imutils import paths
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from keras.datasets import mnist
from sklearn.metrics import classification_report
import keras
from sklearn.preprocessing import LabelEncoder

Using TensorFlow backend.


In [2]:
(x_train, y_train) = mnist.load_data()[0]

In [3]:
x_train.shape

(60000, 28, 28)

In [4]:
x_train = x_train.reshape(x_train.shape[0],28,28,1)

In [5]:
x_train.shape

(60000, 28, 28, 1)

In [6]:
model = load_model('models/hdf5/mnist_lenet_official.hdf5')

In [7]:
sdl = SimpleDatasetLoader()

In [8]:
image_paths = list(paths.list_images('./datasets/digits'))

In [9]:
x_test, y_test = sdl.load(image_paths)

In [10]:
x_test.shape

(523, 28, 28)

In [11]:
y_test.shape

(523,)

In [12]:
x_test = x_test.reshape(x_test.shape[0], 28, 28, 1)

In [13]:
x_test.shape

(523, 28, 28, 1)

In [14]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')

In [15]:
x_train /= 255
x_test /= 255

In [16]:
y_test[:10]

array(['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'], dtype='<U1')

In [17]:
le = LabelEncoder()

In [18]:
y_train[:10]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4], dtype=uint8)

In [19]:
y_test = le.fit_transform(y_test)

In [20]:
y_test[:10]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [21]:
flatten1_layer_model = Model(inputs=model.input, outputs=model.get_layer('flatten_1').output)

In [22]:
features = flatten1_layer_model.predict(x_train)

In [23]:
features.shape

(60000, 9216)

In [24]:
params = {"C": [0.1, 1.0, 10.0, 100.0, 1000.0, 10000.0]}

In [25]:
model = GridSearchCV(LogisticRegression(), params, cv=3, n_jobs=1)

In [26]:
y_train.shape

(60000,)

In [27]:
model.fit(features, y_train)

GridSearchCV(cv=3, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [0.1, 1.0, 10.0, 100.0, 1000.0, 10000.0]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [28]:
model.best_params_

{'C': 1.0}

In [31]:
preds = model.predict(features)

In [33]:
print(classification_report(y_train, preds, target_names=['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00      5923
          1       1.00      1.00      1.00      6742
          2       1.00      1.00      1.00      5958
          3       1.00      1.00      1.00      6131
          4       1.00      1.00      1.00      5842
          5       1.00      1.00      1.00      5421
          6       1.00      1.00      1.00      5918
          7       1.00      1.00      1.00      6265
          8       1.00      1.00      1.00      5851
          9       1.00      1.00      1.00      5949

avg / total       1.00      1.00      1.00     60000



In [34]:
features_test = flatten1_layer_model.predict(x_test)

In [35]:
preds_test = model.predict(features_test)

In [36]:
print(classification_report(y_test, preds_test, target_names=['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']))

             precision    recall  f1-score   support

          0       0.00      0.00      0.00        74
          1       0.00      0.00      0.00        57
          2       1.00      0.07      0.12        61
          3       0.00      0.00      0.00        41
          4       0.00      0.00      0.00        47
          5       0.00      0.00      0.00        39
          6       0.07      0.16      0.10        58
          7       0.54      0.69      0.61        39
          8       0.16      0.89      0.27        47
          9       0.09      0.10      0.10        60

avg / total       0.19      0.17      0.11       523



/home/adam/workspace/venvs/tf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [37]:
y_test

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 7, 7, 7, 7,

In [38]:
x_test1, y_test1 = mnist.load_data()[1]

In [42]:
x_test1 = x_test1.reshape(x_test1.shape[0], 28, 28, 1)
x_test1 = x_test1.astype('float32')

In [43]:
x_test1 = x_test1 / 255

In [44]:
features_test1 = flatten1_layer_model.predict(x_test1)

In [45]:
preds_test1 = model.predict(features_test1)

In [46]:
print(classification_report(y_test1, preds_test1, target_names=['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']))

             precision    recall  f1-score   support

          0       0.00      0.00      0.00       980
          1       0.11      1.00      0.20      1135
          2       0.00      0.00      0.00      1032
          3       0.00      0.00      0.00      1010
          4       0.00      0.00      0.00       982
          5       0.00      0.00      0.00       892
          6       0.00      0.00      0.00       958
          7       0.00      0.00      0.00      1028
          8       0.00      0.00      0.00       974
          9       0.00      0.00      0.00      1009

avg / total       0.01      0.11      0.02     10000



/home/adam/workspace/venvs/tf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [47]:
y_test1

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [48]:
preds_test1

array([1, 1, 1, ..., 1, 1, 1], dtype=uint8)

In [49]:
x_test1.shape

(10000, 28, 28, 1)

In [50]:
y_test1.shape

(10000,)